version: "3.5"
services:
  api:
    container_name: restfulrant-api
    build: .
    ports:
      - 3000:3000
    volumes: 
      - "${PWD}:/usr/src/app"
      - "/usr/src/app/node_modules"
    env_file:
      - docker.api.env
    command: ["./scripts/wait-for-it.sh", "mysql:3306", "--", "npm", "start"]
  mysql:
    container_name: restfulrant-mysql
    image: mysql:5.7
    ports:
      - 27017:27017
    volumes:
      - "${PWD}/mysql/init:/docker-entrypoint-initdb.d/"
      - "${PWD}/mysql/db:/var/lib/mysql"
    env_file:
      - docker.mysql.env

networks:
  default:
    name: restfulrant-network